version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/clean_folder.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/restart_apache.sh
      timeout: 60
      runas: root
